app_root: .
binary_name: tmp-cotizador_sounio_health-build
build_delay: 200ns
build_flags: []
build_path: bin
build_target_path: ./cmd/cotizador_sounio_health
command_env: []
command_flags: []
enable_colors: true
ignored_folders:
- vendor
- log
- logs
- assets
- public
- grifts
- tmp
- bin
- node_modules
- .sass-cache
included_extensions:
- .go
- .env
log_name: ox
